site_name: OtterDocs
<<<<<<< Updated upstream
=======
site_url: https://docs.otterhosting.net
>>>>>>> Stashed changes

theme:
  name: material
  palette:
    scheme: slate

markdown_extensions:
  - admonition